// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNTxPmHaGVGAdGoivp4QVEcvbeOQVp2M8',
    appId: '1:564160382938:web:a894b5ae225fdf96fe22e3',
    messagingSenderId: '564160382938',
    projectId: 'quadravendas-e3c62',
    authDomain: 'quadravendas-e3c62.firebaseapp.com',
    storageBucket: 'quadravendas-e3c62.firebasestorage.app',
    measurementId: 'G-M97ML1QE93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb8BGNhQ1inWxS2NLpL21U3SiX7jAGPGk',
    appId: '1:564160382938:android:2bbb60e140f1b658fe22e3',
    messagingSenderId: '564160382938',
    projectId: 'quadravendas-e3c62',
    storageBucket: 'quadravendas-e3c62.firebasestorage.app',
  );
}
